
title: W.F.C.A.
long_title: Wisconsin Finishing Contractors Association
email: alex@designbymodus.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://192.168.1.110/~Alex/jekyll/wfca"
linkURL: "http://192.168.1.110/~Alex/jekyll/wfca/_site"

# url: "http://designbymodus.com/wfca2016/" # the base hostname & protocol for your site
# linkURL: "http://designbymodus.com/wfca2016/"

# twitter_username: jekyllrb
github_username: alexkademan

# Build settings
markdown: kramdown
# theme: minima



port: 3000
host: 192.168.1.110
destination: ./_site
permalink: /blog/:year/:month/:day/:title/
