
title: WFCA
long_title: Wisconsin Finishing Contractors Association
email: alex@designbymodus.com
description: > # this means to ignore newlines until "baseurl:"
  The Wisconsin Finishing Contractors Association is Wisconsin's premier association of finishing contractors. WFCA members strive to provide their clients with the highest quality workmanship through market based competitive bids in all areas of the finishing disciplines.

# Keep it to 10!
metaKeywords:
  - Commercial Painting
  - Painting Contractors
  - Drywall
  - Commercial Drywallers
  - Drywall Contractors
  - Finish Systems
  - Ceiling Insulation
  - Epoxy
  - Enamels
  - Spray Texture


baseurl: "" # the subpath of your site, e.g. /blog

url: "http://192.168.1.110/~Alex/jekyll/wfca"
linkURL: "http://192.168.1.110/~Alex/jekyll/wfca/_site"

# url: "http://wfcawi.com"
# linkURL: "http://wfcawi.com"

# twitter_username: jekyllrb
github_username: alexkademan

# Build settings
markdown: kramdown
destination: ./_site
port: 3000
host: 192.168.1.110
permalink: /blog/:year/:month/:day/:title/
